//
//  KBGoldenParityMatrix.swift
//  UnaMentisTests
//
//  The golden parity matrix for Knowledge Bowl answer validation
//  (MODULE_SDK_SPEC.md section 13, Phase 4).
//
//  This matrix is the migration contract for lifting KB's algorithmic answer
//  validation into the host `ResponseEvaluationService`. Each case captures a
//  distinct real-world input shape: exact matches, case and punctuation
//  variants, misspellings at varying edit distances, phonetic matches, synonym
//  hits, acceptable-answer hits, near misses that must stay wrong, empty and
//  garbage input, numeric answers, and multi-word answers with token
//  reordering.
//
//  Expected verdicts (`expectedCorrect`, `expectedMatch`) were generated by
//  running the CURRENT `KBAnswerValidator` over this matrix, not written by
//  hand. The same matrix runs against the new host service after the lift; both
//  must agree with these pinned values. See KBValidationGoldenParityTests.
//

import Foundation
@testable import UnaMentis

/// One golden parity case: an input, the question shape it is judged against,
/// the strictness profile, and the pinned expected verdict.
struct KBGoldenParityCase: Sendable {
    let id: String
    let userAnswer: String
    let primary: String
    let acceptable: [String]?
    let answerType: KBAnswerType
    let strictness: KBValidationStrictness
    /// Pinned from the current validator. Filled once, then frozen.
    let expectedCorrect: Bool
    let expectedMatch: String

    func makeQuestion() -> KBQuestion {
        KBQuestion(
            text: "Golden parity question?",
            answer: KBAnswer(primary: primary, acceptable: acceptable, answerType: answerType),
            domain: .science
        )
    }

    /// Build the host EvaluationSpec for this case through the KB bridge, so the
    /// golden suite exercises the exact profile/category/tier mapping the live
    /// KB call site uses.
    func makeEvaluationSpec() -> EvaluationSpec {
        KBEvaluationBridge.spec(
            primary: primary,
            acceptable: acceptable,
            answerType: answerType,
            strictness: strictness
        )
    }
}

/// The full matrix. `standard` strictness is the KB profile the current oral
/// call site uses (the default `KBAnswerValidator()` initializer), so most
/// cases run at `.standard`; a dedicated block exercises `.strict` gating.
enum KBGoldenParityMatrix {
    // Placeholders for expected values are filled after the generator run.
    // Until then they are set to the values captured from the current validator.
    static let cases: [KBGoldenParityCase] = [
        // MARK: - Exact matches
        c("exact-simple", "Paris", "Paris", nil, .text, .standard),
        c("exact-case", "  paris  ", "Paris", nil, .text, .standard),
        c("exact-articles-the", "Moon", "the Moon", nil, .text, .standard),
        c("exact-punctuation", "OHara", "O'Hara", nil, .text, .standard),
        c("exact-trailing-punct", "Einstein.", "Einstein", nil, .text, .standard),
        c("exact-person-simple", "George Washington", "George Washington", nil, .person, .standard),

        // MARK: - Acceptable-answer list hits
        c("acceptable-co2", "CO2", "carbon dioxide", ["CO2"], .text, .standard),
        c("acceptable-usa", "USA", "United States", ["USA", "America"], .place, .standard),
        c("acceptable-case", "america", "United States", ["USA", "America"], .place, .standard),
        c("acceptable-second", "H2O", "water", ["dihydrogen monoxide", "H2O"], .scientific, .standard),

        // MARK: - Misspellings (varying edit distance)
        c("misspell-1del", "Mississipi", "Mississippi", nil, .text, .standard),
        c("misspell-1sub", "Massachusets", "Massachusetts", nil, .text, .standard),
        c("misspell-transpose", "Conneticut", "Connecticut", nil, .text, .standard),
        c("misspell-2edit", "Photosynthysis", "Photosynthesis", nil, .text, .standard),
        c("misspell-short-word", "recieve", "receive", nil, .text, .standard),
        c("misspell-far", "Volcano", "Photosynthesis", nil, .text, .standard),

        // MARK: - Phonetic matches
        c("phonetic-stephen", "Stephen", "Steven", nil, .person, .standard),
        c("phonetic-catherine", "Kathryn", "Catherine", nil, .person, .standard),
        c("phonetic-filadelfia", "Filadelfia", "Philadelphia", nil, .place, .standard),
        c("phonetic-smith", "Smyth", "Smith", nil, .person, .standard),

        // MARK: - Synonym hits (domain dictionaries)
        c("synonym-usa-place", "USA", "United States", nil, .place, .standard),
        c("synonym-h2o-sci", "H2O", "water", nil, .scientific, .standard),
        c("synonym-wwi-hist", "WWI", "World War I", nil, .person, .standard),
        c("synonym-dna-sci", "DNA", "deoxyribonucleic acid", nil, .scientific, .standard),
        c("synonym-uk-place", "UK", "United Kingdom", nil, .place, .standard),

        // MARK: - Multi-word / token reordering
        c("token-reorder-person", "Washington George", "George Washington", nil, .person, .standard),
        c("token-lastcommafirst", "Washington, George", "George Washington", nil, .person, .standard),
        c("token-extra-word", "United States of America", "United States", nil, .place, .standard),
        c("token-subset", "Great Gatsby", "The Great Gatsby", nil, .title, .standard),
        c("token-reorder-3", "King Luther Martin", "Martin Luther King", nil, .person, .standard),

        // MARK: - Numeric answers
        c("numeric-word", "seven", "7", nil, .numeric, .standard),
        c("numeric-commas", "1,000,000", "1000000", nil, .numeric, .standard),
        c("numeric-exact", "42", "42", nil, .numeric, .standard),
        c("numeric-wrong", "43", "42", nil, .numeric, .standard),
        c("numeric-hundred-word", "hundred", "100", nil, .numeric, .standard),

        // MARK: - Titles
        c("title-drop-the", "The Great Gatsby", "Great Gatsby", nil, .title, .standard),
        c("title-drop-subtitle", "Frankenstein: The Modern Prometheus", "Frankenstein", nil, .title, .standard),

        // MARK: - Person titles / honorifics
        c("person-strip-dr", "Dr. Martin Luther King", "Martin Luther King", nil, .person, .standard),
        c("person-strip-mr", "Mr. Charles Dickens", "Charles Dickens", nil, .person, .standard),

        // MARK: - Place abbreviations
        c("place-uk-expand", "UK", "United Kingdom", nil, .place, .standard),
        c("place-mt-expand", "Mt Everest", "Mount Everest", nil, .place, .standard),

        // MARK: - Near misses that MUST stay wrong
        c("nearmiss-cat-dog", "dog", "cat", nil, .text, .standard),
        c("nearmiss-diff-person", "Thomas Jefferson", "George Washington", nil, .person, .standard),
        c("nearmiss-diff-place", "France", "Germany", nil, .place, .standard),
        c("nearmiss-diff-number", "100", "1000", nil, .numeric, .standard),
        c("nearmiss-substring", "car", "carbon", nil, .text, .standard),
        c("nearmiss-close-sci", "helium", "hydrogen", nil, .scientific, .standard),

        // MARK: - Empty / garbage input
        c("empty", "", "Photosynthesis", nil, .text, .standard),
        c("whitespace-only", "   ", "Photosynthesis", nil, .text, .standard),
        c("garbage-symbols", "@#$%^&*", "Photosynthesis", nil, .text, .standard),
        c("garbage-random", "asdfghjkl", "Mitochondria", nil, .text, .standard),

        // MARK: - Strict-profile gating (Colorado strict = no enhanced tiers)
        c("strict-exact-ok", "Mississippi", "Mississippi", nil, .text, .strict),
        // Levenshtein still runs at .strict (only the ENHANCED tiers are gated),
        // so a close typo passes. Contract records the real behavior.
        c("strict-typo-levenshtein-passes", "Mississipi", "Mississippi", nil, .text, .strict),
        c("strict-synonym-rejected", "USA", "United States", nil, .place, .strict),
        c("strict-acceptable-ok", "CO2", "carbon dioxide", ["CO2"], .text, .strict),
        c("strict-nearphonetic-levenshtein-passes", "Steven", "Stephen", nil, .person, .strict),

        // MARK: - Lenient profile (enhanced tiers on; embeddings/LLM absent so
        // behavior equals standard for algorithmic cases)
        c("lenient-synonym-ok", "USA", "United States", nil, .place, .lenient),
        c("lenient-typo-ok", "Mississipi", "Mississippi", nil, .text, .lenient),
        c("lenient-far-wrong", "Volcano", "Photosynthesis", nil, .text, .lenient),

        // MARK: - Scientific formulas
        c("sci-formula-exact", "H2O", "H2O", nil, .scientific, .standard),
        c("sci-nacl-synonym", "NaCl", "salt", nil, .scientific, .standard),
        c("sci-co2-synonym", "CO2", "carbon dioxide", nil, .scientific, .standard),

        // MARK: - Case + punctuation variants on multi-word
        c("multiword-case", "united states of america", "United States of America", nil, .place, .standard),
        c("multiword-punct", "st. louis", "St Louis", nil, .place, .standard)
    ]

    /// Convenience builder. Expected values are populated in a second pass from
    /// the generator output; the initial placeholders below are overwritten by
    /// the pinned table in KBGoldenParityExpected.
    private static func c(
        _ id: String,
        _ userAnswer: String,
        _ primary: String,
        _ acceptable: [String]?,
        _ answerType: KBAnswerType,
        _ strictness: KBValidationStrictness
    ) -> KBGoldenParityCase {
        let expected = KBGoldenParityExpected.table[id] ?? (false, "none")
        return KBGoldenParityCase(
            id: id,
            userAnswer: userAnswer,
            primary: primary,
            acceptable: acceptable,
            answerType: answerType,
            strictness: strictness,
            expectedCorrect: expected.0,
            expectedMatch: expected.1
        )
    }
}
