//
//  KBGoldenParityExpected.swift
//  UnaMentisTests
//
//  Pinned expected verdicts for the golden parity matrix
//  (MODULE_SDK_SPEC.md Phase 4). Generated by running the CURRENT
//  KBAnswerValidator over KBGoldenParityMatrix, then frozen. These values are
//  the migration contract: they must hold before AND after the KB validation
//  lift into the host ResponseEvaluationService.
//
//  Each entry maps a case id to (expectedCorrect, expectedMatchType.rawValue).
//
//  Two entries encode real current-code quirks worth preserving as contract:
//  - `strict-typo-rejected` / `strict-phonetic-rejected` are CORRECT at
//    `.strict` because `.strict` gates only the ENHANCED tiers (synonym,
//    phonetic, n-gram, token, linguistic). Baseline Levenshtein still runs, and
//    both inputs fall within its distance threshold. Only `strictMode` (a
//    separate Config flag) disables Levenshtein.
//  - `nearmiss-diff-number` ("100" vs "1000") is CORRECT because Levenshtein
//    distance is 1, inside the fuzzy threshold. The numeric evaluator inherits
//    the same fuzzy pass the text path uses.
//

enum KBGoldenParityExpected {
    static let table: [String: (Bool, String)] = [
        "exact-simple": (true, "exact"),
        "exact-case": (true, "exact"),
        "exact-articles-the": (true, "exact"),
        "exact-punctuation": (true, "exact"),
        "exact-trailing-punct": (true, "exact"),
        "exact-person-simple": (true, "exact"),
        "acceptable-co2": (true, "acceptable"),
        "acceptable-usa": (true, "acceptable"),
        "acceptable-case": (true, "acceptable"),
        "acceptable-second": (true, "acceptable"),
        "misspell-1del": (true, "fuzzy"),
        "misspell-1sub": (true, "fuzzy"),
        "misspell-transpose": (true, "fuzzy"),
        "misspell-2edit": (true, "fuzzy"),
        "misspell-short-word": (true, "fuzzy"),
        "misspell-far": (false, "none"),
        "phonetic-stephen": (true, "fuzzy"),
        "phonetic-catherine": (true, "fuzzy"),
        "phonetic-filadelfia": (true, "fuzzy"),
        "phonetic-smith": (true, "fuzzy"),
        "synonym-usa-place": (true, "fuzzy"),
        "synonym-h2o-sci": (true, "fuzzy"),
        "synonym-wwi-hist": (true, "fuzzy"),
        "synonym-dna-sci": (true, "fuzzy"),
        "synonym-uk-place": (true, "exact"),
        "token-reorder-person": (true, "fuzzy"),
        "token-lastcommafirst": (true, "exact"),
        "token-extra-word": (true, "fuzzy"),
        "token-subset": (true, "exact"),
        "token-reorder-3": (true, "fuzzy"),
        "numeric-word": (true, "exact"),
        "numeric-commas": (true, "exact"),
        "numeric-exact": (true, "exact"),
        "numeric-wrong": (false, "none"),
        "numeric-hundred-word": (true, "exact"),
        "title-drop-the": (true, "exact"),
        "title-drop-subtitle": (true, "exact"),
        "person-strip-dr": (true, "exact"),
        "person-strip-mr": (true, "exact"),
        "place-uk-expand": (true, "exact"),
        "place-mt-expand": (false, "none"),
        "nearmiss-cat-dog": (false, "none"),
        "nearmiss-diff-person": (false, "none"),
        "nearmiss-diff-place": (false, "none"),
        "nearmiss-diff-number": (true, "fuzzy"),
        "nearmiss-substring": (false, "none"),
        "nearmiss-close-sci": (false, "none"),
        "empty": (false, "none"),
        "whitespace-only": (false, "none"),
        "garbage-symbols": (false, "none"),
        "garbage-random": (false, "none"),
        "strict-exact-ok": (true, "exact"),
        "strict-typo-levenshtein-passes": (true, "fuzzy"),
        "strict-synonym-rejected": (false, "none"),
        "strict-acceptable-ok": (true, "acceptable"),
        "strict-nearphonetic-levenshtein-passes": (true, "fuzzy"),
        "lenient-synonym-ok": (true, "fuzzy"),
        "lenient-typo-ok": (true, "fuzzy"),
        "lenient-far-wrong": (false, "none"),
        "sci-formula-exact": (true, "exact"),
        "sci-nacl-synonym": (true, "fuzzy"),
        "sci-co2-synonym": (true, "fuzzy"),
        "multiword-case": (true, "exact"),
        "multiword-punct": (true, "exact")
    ]
}
