//
//  KBGoldenParityExpected.swift
//  UnaMentisTests
//
//  Pinned expected verdicts for the golden parity matrix
//  (MODULE_SDK_SPEC.md Phase 4). Generated by running the CURRENT
//  KBAnswerValidator over KBGoldenParityMatrix, then frozen. These values are
//  the migration contract: they must hold before AND after the KB validation
//  lift into the host ResponseEvaluationService.
//
//  Each entry maps a case id to (expectedCorrect, expectedMatchType.rawValue).
//
//  DELIBERATE PROFILE CHANGE (2026-08, RFC 0004 item 6). Two entries used to
//  pin false accepts that the lifted KBAnswerValidator produced, and the fuzzy
//  tolerance was tightened to remove them. Both changed values below are the
//  ONLY differences from the originally generated table:
//
//  - `nearmiss-diff-number` ("100" vs "1000") was CORRECT: the numeric answer
//    took the text fuzzy path, where a Levenshtein distance of 1 sat inside the
//    two-edit floor. A digit edit changes the VALUE, so numeric answers are now
//    exact or tolerance-based only and this case is INCORRECT.
//  - `strict-nearphonetic-rejected` ("Steven" vs "Stephen" under the Colorado
//    strict profile) was CORRECT: `.strict` gates the enhanced tiers, including
//    phonetics, but the two-edit floor let the phonetic variant through the
//    baseline Levenshtein tier anyway. With the tolerance a pure fraction of
//    the answer length (7 characters at 20 percent tolerates one edit, the pair
//    differs by two), strict now means what it says and the case is INCORRECT.
//
//  Everything else still holds exactly as generated from the legacy validator.
//

enum KBGoldenParityExpected {
    static let table: [String: (Bool, String)] = [
        "exact-simple": (true, "exact"),
        "exact-case": (true, "exact"),
        "exact-articles-the": (true, "exact"),
        "exact-punctuation": (true, "exact"),
        "exact-trailing-punct": (true, "exact"),
        "exact-person-simple": (true, "exact"),
        "acceptable-co2": (true, "acceptable"),
        "acceptable-usa": (true, "acceptable"),
        "acceptable-case": (true, "acceptable"),
        "acceptable-second": (true, "acceptable"),
        "misspell-1del": (true, "fuzzy"),
        "misspell-1sub": (true, "fuzzy"),
        "misspell-transpose": (true, "fuzzy"),
        "misspell-2edit": (true, "fuzzy"),
        "misspell-short-word": (true, "fuzzy"),
        "misspell-far": (false, "none"),
        "phonetic-stephen": (true, "fuzzy"),
        "phonetic-catherine": (true, "fuzzy"),
        "phonetic-filadelfia": (true, "fuzzy"),
        "phonetic-smith": (true, "fuzzy"),
        "synonym-usa-place": (true, "fuzzy"),
        "synonym-h2o-sci": (true, "fuzzy"),
        "synonym-wwi-hist": (true, "fuzzy"),
        "synonym-dna-sci": (true, "fuzzy"),
        "synonym-uk-place": (true, "exact"),
        "token-reorder-person": (true, "fuzzy"),
        "token-lastcommafirst": (true, "exact"),
        "token-extra-word": (true, "fuzzy"),
        "token-subset": (true, "exact"),
        "token-reorder-3": (true, "fuzzy"),
        "numeric-word": (true, "exact"),
        "numeric-commas": (true, "exact"),
        "numeric-exact": (true, "exact"),
        "numeric-wrong": (false, "none"),
        "numeric-hundred-word": (true, "exact"),
        "title-drop-the": (true, "exact"),
        "title-drop-subtitle": (true, "exact"),
        "person-strip-dr": (true, "exact"),
        "person-strip-mr": (true, "exact"),
        "place-uk-expand": (true, "exact"),
        "place-mt-expand": (false, "none"),
        "nearmiss-cat-dog": (false, "none"),
        "nearmiss-diff-person": (false, "none"),
        "nearmiss-diff-place": (false, "none"),
        "nearmiss-diff-number": (false, "none"),
        "nearmiss-substring": (false, "none"),
        // Real competition answers a one-edit or two-edit tolerance used to
        // accept. Pinned here so the tightened tolerance cannot regress.
        "nearmiss-iran-iraq": (false, "none"),
        "nearmiss-austria-australia": (false, "none"),
        "nearmiss-close-sci": (false, "none"),
        "empty": (false, "none"),
        "whitespace-only": (false, "none"),
        "garbage-symbols": (false, "none"),
        "garbage-random": (false, "none"),
        "strict-exact-ok": (true, "exact"),
        "strict-typo-levenshtein-passes": (true, "fuzzy"),
        "strict-synonym-rejected": (false, "none"),
        "strict-acceptable-ok": (true, "acceptable"),
        "strict-nearphonetic-rejected": (false, "none"),
        "lenient-synonym-ok": (true, "fuzzy"),
        "lenient-typo-ok": (true, "fuzzy"),
        "lenient-far-wrong": (false, "none"),
        "sci-formula-exact": (true, "exact"),
        "sci-nacl-synonym": (true, "fuzzy"),
        "sci-co2-synonym": (true, "fuzzy"),
        "multiword-case": (true, "exact"),
        "multiword-punct": (true, "exact")
    ]
}
