//
//  KBValidationGoldenParityTests.swift
//  UnaMentisTests
//
//  Golden parity suite for the Knowledge Bowl answer-validation migration
//  (MODULE_SDK_SPEC.md section 13, Phase 4). This is the migration contract.
//
//  It runs the full KBGoldenParityMatrix through the host evaluation service
//  and asserts each verdict matches the pinned KBGoldenParityExpected table.
//
//  The pinned table was generated by running the legacy `KBAnswerValidator`
//  (the code that was lifted) over this exact matrix BEFORE the lift, so a green
//  run here proves the host `DefaultResponseEvaluationService` reproduces the
//  old KB behavior case for case. This is the Phase 4 exit criterion
//  (MODULE_SDK_SPEC.md section 13).
//

import XCTest
@testable import UnaMentis

@available(iOS 18.0, *)
final class KBValidationGoldenParityTests: XCTestCase {

    /// The host ResponseEvaluationService reproduces KB behavior across the full
    /// matrix. This is the Phase 4 exit criterion.
    func testHostEvaluationServiceMatchesGoldenTable() async {
        let service = DefaultResponseEvaluationService()
        for kase in KBGoldenParityMatrix.cases {
            let spec = kase.makeEvaluationSpec()
            let response = LearnerResponse(text: kase.userAnswer)
            let result = await service.evaluate(response, against: spec)

            let verdictCorrect = result.verdict == .correct
            XCTAssertEqual(
                verdictCorrect, kase.expectedCorrect,
                "[host] verdict drift for '\(kase.id)' (input: '\(kase.userAnswer)')"
            )
            XCTAssertEqual(
                result.matchType.rawValue, kase.expectedMatch,
                "[host] match-type drift for '\(kase.id)' (input: '\(kase.userAnswer)')"
            )
        }
    }
}
